# Development Docker Compose (without Docker-in-Docker)
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:5000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - code-volume:/app/code
    environment:
      - USE_DOCKER=false  # Use local execution for development
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  code-volume: