# Production Docker Compose
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - code-volume:/app/code
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USE_DOCKER=true
      - NODE_ENV=production
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  app-network:
    driver: bridge

volumes:
  code-volume: